### ISSUE TITLE
Number of thread used in parallel case

### ISSUE THREAD

**Issue by AlexRaiteri** [AleCandido/quad#15]
Optional number of thread used in parallel case could be introduced. 
At the moment rayon use all threads available.

**Comment by AleCandido** [comment]
This has definitely some priority, since we should be able to unify the parallel and non-parallel in a single implementation, where the sequential one is just the parallel on a single-thread (if `rayon` has overhead even in that case, we should consider implementing an iterator that uses `rayon` only for more than one thread, but I hope it is doing this internally).
